#!/usr/bin/env bash

_debug() {
    [ -z "$GITCRYPTDEBUG" ] || echo -e "GCDBG: ${GDBGTAB} ${1}"
}

[ "$GITCRYPT_AFFECTED_FILES" == "*" ] && _debug " [$0] ALL files"
[ "$GITCRYPT_AFFECTED_FILES" == "*" ] && (GITCRYPT_AFFECTED_FILES=`git ls-tree --name-only --full-tree -r $GIT_COMMIT` || exit 1)

IFS="
"

export GDBGTAB="${GDBGTAB}  "

echo f1
for x in $GITCRYPT_AFFECTED_FILES; do
echo f2
    cmd="cat \"$x\" | $@ > \"$x.tmp\""
    if [ -f "$x" ]; then
echo f3
        _debug "- $cmd"
echo f4
        eval $cmd || continue 
echo f5
        cat "$x.tmp" > "$x" 
        rm -f "$x.tmp"
    fi
done

export GDBGTAB={GDBGTAB/\ \ /}
