#!/usr/bin/env bash

_debug() {
    [ -z "$GITCRYPTDEBUG" ] || echo -e "GCDBG: ${GCDBGTAB} ${1}"
}

[ "$GITCRYPT_AFFECTED_FILES" == "*" ] && _debug " [$0] ALL files"
[ "$GITCRYPT_AFFECTED_FILES" == "*" ] && (GITCRYPT_AFFECTED_FILES=`git ls-tree --name-only --full-tree -r $GIT_COMMIT` || exit 1)

IFS="
"

export GCDBGTAB="${GCDBGTAB}  "

for x in $GITCRYPT_AFFECTED_FILES; do
    cmd="cat \"$x\" | $@ > \"$x.tmp\""
    if [ -f "$x" ]; then
        _debug "- $cmd"
        eval $cmd || continue 
        cat "$x.tmp" > "$x" 
        rm -f "$x.tmp"
    fi
done

export GCDBGTAB={GCDBGTAB/\ \ /}
